version: "2"

networks:
  sub-services:
    driver: bridge
    internal: true
  web-services:
    driver: bridge
    internal: true

volumes:
  recorder-storage:
  stream-socket:

services:
  queue:
    image: rabbitmq:3
    networks: [sub-services]
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3

  recorder:
    build: ./recorder
    networks: [sub-services]
    depends_on:
      queue:
        condition: service_healthy
    environment:
      AUREC_RABBITMQ_IP: queue
      AUREC_RABBITMQ_NOTIFICATION_QUEUE: "notifications"
      # must match volume path, otherwise the app will store videos in /tmp
      AUREC_VIDEO_LOCATION: "/var/lib/aurec-recorder/videos"
      AUREC_STREAM_SOCKET: "/run/aurec-recorder/stream/socket"
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - recorder-storage:/var/lib/aurec-recorder/videos
      - stream-socket:/run/aurec-recorder/stream

  streamer:
    build: ./streamer
    networks: [web-services]
    depends_on:
      recorder:
        condition: service_started
    environment:
      AUREC_STREAM_SOCKET: "/run/aurec-recorder/stream/socket"
    volumes:
      - stream-socket:/run/aurec-recorder/stream

  video-api:
    build: ./video-api
    networks: [web-services]
    depends_on:
      recorder:
        condition: service_started
    environment:
      AUREC_VIDEO_LOCATION: "/var/lib/aurec-recorder/videos"
    volumes:
      - recorder-storage:/var/lib/aurec-recorder/videos

  gateway:
    build: ./gateway
    networks: [web-services, default]
    depends_on: [streamer]
    ports:
      - 80:8080
